import { NextPage } from 'next';
import Head from 'next/head';

const Index: NextPage = () => {
  return (
    <div className="container">
      <Head>
        <title>ItsMateo20 | AboutMe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid">
        <div className="card">
          <a className="titlemove; titlecolor"><b>Hi, I'm ItsMateo20.</b></a>
          <a className="descriptionmove; descriptioncolor">I am interested in programming, The 4 recent projects are <a className="descriptioncolor" href="http://top.gg/bot/831829384884518923">Draid</a> and websites like <a className="descriptioncolor" href="http://draid.ddns.net">Draid</a>, <a className="descriptioncolor" href="http://gibporad.ddns.net">Giboon poradnia</a> and this site</a>
        </div>
      </div>
    </div>
  )
}

export default Index;
